---
- import_playbook: ../common/verify.yml

- name: Check log for correct config of controller-mesh edge nodes
  hosts: all
  tasks:
  - assert:
      that:
        - qdrlog_content.find('Router started in Edge mode') != -1
    name: Router started in Edge mode

  - assert:
      that:
        - >-
          qdrlog_content is
          search('Configured Connector: 10.0.0.20:5668 proto=any, role=edge')
        - >-
          qdrlog_content is
          search('Configured Connector: 10.0.0.30:5668 proto=any, role=edge')
    name: Connectors to internal mesh configured

  - assert:
      that:
        - >-
          qdrlog_content is not
          search('stf-default-interconnect-5671-service-telemetry.example.com')
    name: External connector correctly supressed for mesh edge nodes
