---
# Copyright 2021 Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- name: create OVN BGP agent directories
  ansible.builtin.file:
    path: "{{ tripleo_frr_ovn_bgp_agent_config_basedir }}/etc/ovn-bgp-agent/rootwrap.d"
    recurse: true
    state: directory
    selevel: s0
    setype: container_file_t

- name: configure OVN BGP agent
  ansible.builtin.template:
    src: ovn-bgp-agent.conf.j2
    dest: "{{ tripleo_frr_ovn_bgp_agent_config_basedir }}/etc/ovn-bgp-agent/bgp-agent.conf"
    mode: '640'
    selevel: s0
    setype: container_file_t
  register: _ovn_bgp_agent_config_result

- name: configure OVN BGP agent rootwrap
  ansible.builtin.template:
    src: rootwrap.conf.j2
    dest: "{{ tripleo_frr_ovn_bgp_agent_config_basedir }}/etc/ovn-bgp-agent/rootwrap.conf"
    mode: '640'
    selevel: s0
    setype: container_file_t
  register: _ovn_bgp_agent_rootwrap_result

- name: configure OVN BGP agent rootwrap filters
  ansible.builtin.template:
    src: rootwrap.filters.j2
    dest: "{{ tripleo_frr_ovn_bgp_agent_config_basedir }}/etc/ovn-bgp-agent/rootwrap.d/rootwrap.filters"
    mode: '640'
    selevel: s0
    setype: container_file_t
  register: _ovn_bgp_agent_rootwrap_filters_result

- name: configure ovs manager
  command: ovs-vsctl set-manager "{{ tripleo_frr_ovn_bgp_agent_ovs_manager }}"


# ['datacenter:br-ex', 'foo:br-vlan']
- name: Set ipv4 proxy_arp for each physical nic used in bridge mappings
  sysctl:
    name: "net.ipv4.conf.{{ item.split(':')[1] }}.proxy_arp"
    value: 1
    sysctl_set: true
    sysctl_file: /etc/sysctl.d/99-tripleo-ovn-bgp-agent.conf
    state: present
    reload: true
  loop: "{{ tripleo_frr_ovn_bgp_agent_bridge_mappings }}"

- name: Set ipv6 proxy_ndp for each physical nic used in bridge mappings
  sysctl:
    name: "net.ipv6.conf.{{ item.split(':')[1] }}.proxy_ndp"
    value: 1
    sysctl_set: true
    sysctl_file: /etc/sysctl.d/99-tripleo-ovn-bgp-agent.conf
    state: present
    reload: true
  loop: "{{ tripleo_frr_ovn_bgp_agent_bridge_mappings }}"

- name: restart OVN BGP agent
  when:
    - _ovn_bgp_agent_config_result.changed or
      _ovn_bgp_agent_rootwrap_result.changed or
      _ovn_bgp_agent_rootwrap_filters_result.changed
  block:
    - name: check if tripleo_ovn_bgp_agent systemd service is active
      shell: systemctl is-active --quiet tripleo_ovn_bgp_agent
      failed_when: false
      register: ovn_bgp_agent_active_service

    - name: restart tripleo_ovn_bgp_agent container
      systemd:
        name: tripleo_ovn_bgp_agent
        state: restarted
      when:
        - ovn_bgp_agent_active_service.rc == 0
