#!/usr/bin/env bash

TIMEOUT=${1:-90}
PARALLEL=${2:-10}

if command -v dnf >/dev/null;then
    if command -v podman >/dev/null; then
        containers=$(podman ps --filter label=managed_by=tripleo_ansible --format {{.Names}})
        for c in $containers; do
            logger -p warning "WARNING ($c) Container $c managed by tripleo-ansible is not stopped yet"
            logger -p warning "WARNING ($c) Check systemd logs: journalctl -u tripleo_$c"
        done
    fi
else
    if command -v docker >/dev/null; then
        /usr/bin/docker ps --format \"{{.Names}}\" --filter "label=managed_by=tripleo_ansible" | \
          /usr/bin/xargs -n 1 -P $PARALLEL /usr/bin/docker stop --time=$TIMEOUT
    fi
fi
