#!/usr/bin/env bash
# Copyright 2019 Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.


## Shell Opts ----------------------------------------------------------------

set -o pipefail
set -xeuo

## Vars ----------------------------------------------------------------------

export PROJECT_DIR="$(dirname $(readlink -f ${BASH_SOURCE[0]}))/../"
export ROLE_NAME="${ROLE_NAME:-$1}"

## Main ----------------------------------------------------------------------

# Source distribution information
source /etc/os-release || source /usr/lib/os-release
RHT_PKG_MGR=$(command -v dnf || command -v yum)
PYTHON_EXEC=$(command -v python3 || command -v python)

# Install the one requirement we need to run any local test
case "${ID,,}" in
    amzn|rhel|centos|fedora)
        sudo "${RHT_PKG_MGR}" install -y python*-virtualenv
        ;;
esac

# Create a virtual env
"${PYTHON_EXEC}" -m virtualenv --system-site-packages "${HOME}/test-python"

# Install local requirements
"${HOME}/test-python/bin/pip" install \
                              -r "${PROJECT_DIR}/requirements.txt" \
                              -r "${PROJECT_DIR}/test-requirements.txt" \
                              -r "${PROJECT_DIR}/molecule-requirements.txt"

# Run bindep
PS1="[\u@\h \W]\$" source "${HOME}/test-python/bin/activate"
"${PROJECT_DIR}/scripts/bindep-install"

# Run local test
source "${PROJECT_DIR}/ansible-test-env.rc"
ansible-playbook -i "${PROJECT_DIR}/tests/hosts.ini" \
                 -e "ansible_user=${USER}" \
                 -e "ansible_user_dir=${HOME}" \
                 "${PROJECT_DIR}/tripleo_ansible/playbooks/prepare-test-host.yml"

# Run test
pushd "${PROJECT_DIR}/tripleo_ansible/roles/${ROLE_NAME}"
    molecule test --all
popd
