---
- import_playbook: ../common/converge.yml

- name: Converge edge-only config
  hosts: all
  tasks:
    - name: Invoke tripleo_metrics_qdr for edge-only
      include_role:
        name: "{{ playbook_dir }}/../../../tripleo_metrics_qdr"
        tasks_from: create_config
      vars:
        tripleo_metrics_qdr_connectors:
          - host: stf-default-interconnect-5671-service-telemetry.example.com
            port: 443
            role: edge
            sslProfile: sslProfile
            verifyHostname: false
        controller_node_ips: 10.0.0.20,10.0.0.30,10.0.0.40
        ctlplane_ip: 10.0.0.10
        internal_api_ip: "{{ ansible_default_ipv4.address }}"
        service_net_map:
          standalone_metrics_qdr_network: internal_api
        tripleo_role_name: Standalone
