FROM centos:stream9
LABEL maintainer="dev@cloudesire.com"

ENV OS_RELEASE=yoga

RUN yum clean all \
  && yum -y update \
  && yum -y install centos-release-openstack-${OS_RELEASE} \
  && yum -y install openstack-keystone python-openstackclient \
  && yum clean all

COPY start_keystone.sh /
EXPOSE 5000 35357

CMD ["/start_keystone.sh"]
