---
# Copyright 2019 Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- name: Prepare
  hosts: localhost
  become: true
  connection: local
  pre_tasks:
    - name: Disable SELinux
      selinux:
        state: disabled

  tasks:
    - include_role:
        name: test_deps
      vars:
        test_deps_setup_tripleo: true
        test_deps_extra_packages:
          - python3-openstacksdk
          - python3-openstackclient
          - python3-keystoneclient
          - ansible

    - name: Build keystone container
      shell: "podman build -t keystone-img -f {{ playbook_dir }}/Dockerfile.keystone ."
      become: false

    - name: Create test containers
      podman_container:
        name: keystone-podman
        image: keystone-img
        detach: true
        ports:
          - "5000:5000"
      become: false

    - name: Give keystone time to go up
      pause:
        seconds: 30
