---
driver:
  name: docker

log: true

platforms:
  - name: centos7
    hostname: centos7
    image: centos:7
    dockerfile: Dockerfile
    pkg_extras: python-setuptools
    easy_install:
      - pip
    environment: &env
      http_proxy: "{{ lookup('env', 'http_proxy') }}"
      https_proxy: "{{ lookup('env', 'https_proxy') }}"
    command: >-
      /sbin/init &&
      /bin/mkdir -p /var/run/dbus &&
      /usr/bin/dbus-uuidgen > /var/lib/dbus/machine-id &&
      /usr/bin/dbus-daemon --config-file=/usr/share/dbus-1/system.conf
    tmpfs:
      - /run
      - /tmp
    capabilities:
      - ALL
    volumes:
      - /dev:/dev
      - /lib/modules:/lib/modules

  - name: fedora28
    hostname: fedora28
    image: fedora:28
    dockerfile: Dockerfile
    pkg_extras: python*-setuptools
    environment:
      http_proxy: "{{ lookup('env', 'http_proxy') }}"
      https_proxy: "{{ lookup('env', 'https_proxy') }}"
    command: >-
      /sbin/init &&
      /bin/mkdir -p /var/run/dbus &&
      /usr/bin/dbus-uuidgen > /var/lib/dbus/machine-id &&
      /usr/bin/dbus-daemon --config-file=/usr/share/dbus-1/system.conf
    privileged: true
    tmpfs:
      - /run
      - /tmp
    capabilities:
      - ALL
    volumes:
      - /dev:/dev
      - /lib/modules:/lib/modules

provisioner:
  name: ansible
  log: true
  env:
    ANSIBLE_STDOUT_CALLBACK: yaml

scenario:
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - verify
    - destroy

lint:
  enabled: false

verifier:
  name: testinfra
  lint:
    name: flake8
